remote: true

experienceLevel:
 internship: true
 entry: true
 associate: true
 mid-senior level: false
 director: false
 executive: false

jobTypes:
 full-time: true
 contract: true
 part-time: false
 temporary: false
 internship: true
 other: false
 volunteer: false

date:
 all time: false
 month: false
 week: false
 24 hours: true

positions:
  - Blockchain




locations:
  - United States
  - Raleigh, NC



distance: 100

companyBlacklist:
  - ThoroughCare
  - VIVA USA Inc.

titleBlacklist:
  - service coordinator
  - customer service representative
  - Solar Project Coordinator
  - Field Support Specialist